repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - args:
    - --allow-multiple-documents
    exclude: Deployments/
    id: check-yaml
  - id: debug-statements
  - args:
    - --allow-missing-credentials
    id: detect-aws-credentials
  - args:
    - --fix=no
    id: mixed-line-ending
  - args:
    - --branch
    - master
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --py310-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
- hooks:
  - id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 3.7.8
- hooks:
  - id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
- hooks:
  - id: black
    language_version: python3.10
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - id: codespell
  repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
- hooks:
  - id: mypy
    language_version: python3.11
    exclude: ^old_src_die/.*
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
